name: Build Release APK on PR Comment

on:
    issue_comment:
        types: [created]

jobs:
    build:
        if: github.event.issue.pull_request != null && github.event.comment.body == '/build-apk'
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.issue.pull_request.head.ref }}
                  repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                  distribution: "zulu"
                  java-version: "17"

            - name: Recreate keystore.properties
              run: |
                  echo "${{ secrets.KEYSTORE_PROPERTIES }}" > keystore.properties

            - name: Set up Gradle
              uses: gradle/gradle-build-action@v2

            - name: Build release APK
              run: ./gradlew assembleRelease

            - name: Rename APK with PR ID and run ID
              run: |
                  mv app/build/outputs/apk/release/app-release.apk "Staucktion-debug-${{ github.event.issue.number }}-${{ github.run_id }}.apk"

            - name: Upload APK
              uses: actions/upload-artifact@v4
              with:
                  name: Staucktion-APK
                  path: Staucktion-debug-${{ github.event.issue.number }}-${{ github.run_id }}.apk

            - name: Comment with download link
              if: success()
              uses: actions/github-script@v6
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      const prNumber = context.issue.number;
                      const runId = context.runId;
                      const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;
                      github.rest.issues.createComment({
                        issue_number: prNumber,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `✅ APK build is done! [Download it here](${url}) (look in "Artifacts" section)`
                      });
